# CI de Nível 02 - Disparo agendado

name: 'Execução Agendada'

# regras de disparo (gatilhos/triggers)
# gatilho exec agendada = schedule

on:
  schedule:
    - cron: '0 11 * 6 *'

# trabalho/tarefas dentro de pipelines = jobs
jobs:
  e2e-tests:
    # maquina que o job vai executar
    runs-on: ubuntu-latest

    # passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      # instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalação das dependências
      - name: Instalando dependências
        run: yarn

      # instalação do Playwright // Para realiar os testes deste projeto, são necessários apenas o uso do Mocha e assert
      #- name: Instalando Playwright
      #  run: yarn playwright install

      # executar os testes e2e
      - name: Executando Testes E2E
        run: yarn run e2e
